NAME 		= libft.a
NAMEASM 	= libasm.a
CC 			= gcc
NA			= nasm
NA_FLAGS	= -g -f macho64
FLAGS = -Wall -Wextra -Werror -c
SRC = ft_atoi.c ft_bzero.c ft_isalnum.c ft_isalpha.c ft_isascii.c ft_isdigit.c \
ft_isprint.c ft_memccpy.c ft_memchr.c ft_memcmp.c ft_memcpy.c ft_memmove.c \
ft_memset.c ft_strchr.c ft_strrchr.c ft_strdup.c ft_calloc.c ft_strlcpy.c \
ft_strlcat.c ft_strlen.c ft_strncmp.c ft_strnstr.c ft_tolower.c ft_toupper.c \
ft_substr.c ft_strjoin.c ft_strtrim.c ft_split.c ft_itoa.c ft_strmapi.c \
ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c stack.c \
get_next_line.c get_next_line_utils.c ft_lstnew.c ft_lstadd_front.c \
ft_lstsize.c ft_lstlast.c ft_lstadd_back.c ft_lstdelone.c ft_lstclear.c \
ft_lstiter.c ft_lstmap.c ft_int_max.c new_stack.c
OBJ = $(SRC:.c=.o)

SRCS		= ft_strlen.s \
			 ft_strcpy.s \
			 ft_strcmp.s \
			 ft_write.s \
			 ft_read.s \
			 ft_strdup.s

OBJASM		= $(SRCS:.s=.o)

.PHONY: all clean fclean re

all: $(NAME) $(NAMEASM)


$(NAME): $(OBJ)
	ar rc $(NAME) $(OBJ)

$(NAMEASM): $(OBJASM)
	ar rc $(NAMEASM) $(OBJASM)
	ar rc $(NAME) $(OBJASM)
	ranlib $(NAME)

.c.o:
	$(CC) $(FLAGS) $< -o $@

.s.o:
	$(NA) $(NA_FLAGS) $< -o $@

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: clean fclean all
